regenweapon:
 TypeForSeconds: multiply
 secondstoworkwith: 1
 defaultseconds: 1
 TypeForAmplifier: add
 amplifiertoworkwith: 1
 defaultamplifier: 1
 MaximumTierLevel: -1
extremeknocbackarrow:
 TypeForVelocity: add
 velocitytoworkwith: 1
 defaultvelocity: 1