regenweapon:
 TypeForSeconds: multiply
 secondstoworkwith: 1
 defaultseconds: 1
 TypeForAmplifier: add
 amplifiertoworkwith: 1
 defaultamplifier: 1
 MaximumTierLevel: -1
 Disabled: false
extremeknocbackarrow:
 TypeForVelocity: add
 velocitytoworkwith: 1
 defaultvelocity: 1
 MaximumTierLevel: -1
other:
 currencysymbol: $
 logmessage: :PLAYER was lucky while fishing and received :MONEY!
 playermessage: You were lucky and received :MONEY!
 sendplayermessages: true
 logtoconsole: true
 sidecurrencygoeson: left