Regen:
 I:
  seconds: 1
  amplifier: 3
 II:
  seconds: 2
  amplifier: 3
 III:
  seconds: 3
  amplifier: 3
 IV:
  seconds: 4
  amplifier: 3
 V:
  seconds: 5
  amplifier: 3
Poison:
 I:
  seconds:  3
  amplifier: 1
 II:
  seconds: 4
  amplifier: 2
 III:
  seconds: 5
  amplifier: 3
 IV:
  seconds: 6
  amplifier: 4
 V:
  seconds: 7
  amplifier: 5
Wither:
 I: 
  seconds: 3
  amplifier: 1
 II:
  seconds: 4
  amplifier: 2
 III:
  seconds: 5
  amplifier: 3
 IV:
  seconds: 6
  amplifier: 4
 V:
  seconds: 7
  amplifier: 5
Blind:
 I:
  seconds: 1 
  amplifier: 1
 II:
  seconds: 2
  amplifier: 2
 III:
  seconds: 3
  amplifier: 3
 IV: 
  seconds: 4
  amplifier: 4
 V:
  seconds: 5
  amplifier: 5
Leechhunger:
 I:
  seconds: 
   saturation: 0.1
   hunger: 1.5
  amplifier:
   saturation: 1
   hunger: 4
 II:
  seconds: 
   saturation: 0.2
   hunger: 3
  amplifier:
   saturation: 1
   hunger: 4
 III:
  seconds: 
   saturation: 0.3
   hunger: 4.5
  amplifier:
   saturation: 1
   hunger: 4
 IV:
  seconds: 
   saturation: 0.4
   hunger: 6
  amplifier:
   saturation: 1
   hunger: 4
 V:
  seconds: 
   saturation: 0.5
   hunger: 7.5
  amplifier:
   saturation: 1
   hunger: 4
Nausea:
 I:
  seconds: 1
  amplifier: 1
 II:
  seconds: 2
  amplifier: 1
 III:
  seconds: 3
  amplifier: 1
 IV:
  seconds: 4
  amplifier: 1
 V:
  seconds: 5
  amplifier: 1
Resistance:
 I:
  seconds: 1.5
  amplifier: 1
 II:
  seconds: 3
  amplifier: 1
 III:
  seconds: 4.5
  amplifier: 1
 IV:
  seconds: 6
  amplifier: 1
 V:
  seconds: 7.5
  amplifier: 1
Strength:
 I:
  seconds: 2
  amplifier: 1
 II:
  seconds: 3
  amplifier: 2
 III:
  seconds: 4
  amplifier: 3
 IV:
  seconds: 5
  amplifier: 4
 V:
  seconds: 6
  amplifier: 5
Slow:
 I:
  seconds: 1
  amplifier: 1
 II:
  seconds: 2
  amplifier: 2
 III:
  seconds: 3
  amplifier: 3
 IV:
  seconds: 4
  amplifier: 4
 V:
  seconds: 5
  amplifier: 5
Speed:
 I:
  seconds: 2
  amplifier: 1
 II:
  seconds: 3
  amplifier: 2
 III:
  seconds: 4
  amplifier: 3
 IV:
  seconds: 5
  amplifier: 4
 V:
  seconds: 6
  amplifier: 5
Invisibility:
 I:
  seconds: 5
  amplifier: 1
 II:
  seconds: 7.5
  amplifier: 1
 III:
  seconds: 10
  amplifier: 1
 IV:
  seconds: 12.5
  amplifier: 1
 V:
  seconds: 15
  amplifier: 1