package io.github.searchndstroy.customenchnats.common;

public enum AddEnchantType {

	REGENWEAPON, 
	WITHERWEAPON, 
	POISONWEAPON, 
	BLINDNESSWEAPON, 
	NAUSEAWEAPON, 
	RESISTANCEWEAPON, 
	LEECHHUNGERWEAPON, 
	SPEEDBOOTS, 
	INVISIBILITYWEAPON,
	STRENGTHHELMET,
	REGENFOOD,
	RESISTANCEFOOD,
	HEALTHBOOSTFOOD,
	ABSORPTIONFOOD,

}
